/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InstructorService } from "../instructor.service";
import { InstructorCreateInput } from "./InstructorCreateInput";
import { Instructor } from "./Instructor";
import { InstructorFindManyArgs } from "./InstructorFindManyArgs";
import { InstructorWhereUniqueInput } from "./InstructorWhereUniqueInput";
import { InstructorUpdateInput } from "./InstructorUpdateInput";
import { CourseFindManyArgs } from "../../course/base/CourseFindManyArgs";
import { Course } from "../../course/base/Course";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import { LiveSessionFindManyArgs } from "../../liveSession/base/LiveSessionFindManyArgs";
import { LiveSession } from "../../liveSession/base/LiveSession";
import { LiveSessionWhereUniqueInput } from "../../liveSession/base/LiveSessionWhereUniqueInput";

export class InstructorControllerBase {
  constructor(protected readonly service: InstructorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Instructor })
  async createInstructor(
    @common.Body() data: InstructorCreateInput
  ): Promise<Instructor> {
    return await this.service.createInstructor({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Instructor] })
  @ApiNestedQuery(InstructorFindManyArgs)
  async instructors(@common.Req() request: Request): Promise<Instructor[]> {
    const args = plainToClass(InstructorFindManyArgs, request.query);
    return this.service.instructors({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Instructor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async instructor(
    @common.Param() params: InstructorWhereUniqueInput
  ): Promise<Instructor | null> {
    const result = await this.service.instructor({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Instructor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInstructor(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() data: InstructorUpdateInput
  ): Promise<Instructor | null> {
    try {
      return await this.service.updateInstructor({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Instructor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInstructor(
    @common.Param() params: InstructorWhereUniqueInput
  ): Promise<Instructor | null> {
    try {
      return await this.service.deleteInstructor({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/courses")
  @ApiNestedQuery(CourseFindManyArgs)
  async findCourses(
    @common.Req() request: Request,
    @common.Param() params: InstructorWhereUniqueInput
  ): Promise<Course[]> {
    const query = plainToClass(CourseFindManyArgs, request.query);
    const results = await this.service.findCourses(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        instructor: {
          select: {
            id: true,
          },
        },

        price: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courses")
  async connectCourses(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        connect: body,
      },
    };
    await this.service.updateInstructor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courses")
  async updateCourses(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        set: body,
      },
    };
    await this.service.updateInstructor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courses")
  async disconnectCourses(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        disconnect: body,
      },
    };
    await this.service.updateInstructor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/liveSessions")
  @ApiNestedQuery(LiveSessionFindManyArgs)
  async findLiveSessions(
    @common.Req() request: Request,
    @common.Param() params: InstructorWhereUniqueInput
  ): Promise<LiveSession[]> {
    const query = plainToClass(LiveSessionFindManyArgs, request.query);
    const results = await this.service.findLiveSessions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        instructor: {
          select: {
            id: true,
          },
        },

        scheduledTime: true,
        title: true,
        updatedAt: true,
        zoomLink: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/liveSessions")
  async connectLiveSessions(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() body: LiveSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      liveSessions: {
        connect: body,
      },
    };
    await this.service.updateInstructor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/liveSessions")
  async updateLiveSessions(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() body: LiveSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      liveSessions: {
        set: body,
      },
    };
    await this.service.updateInstructor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/liveSessions")
  async disconnectLiveSessions(
    @common.Param() params: InstructorWhereUniqueInput,
    @common.Body() body: LiveSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      liveSessions: {
        disconnect: body,
      },
    };
    await this.service.updateInstructor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
